version: "3.9"
services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - prefect-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: always
    volumes:
      - prefect-server:/root/.prefect
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_API_URL=http://127.0.0.1:4200/api
    ports:
      - "4200:4200"
    depends_on:
      - postgres

  prefect-worker:
    image: prefecthq/prefect:3-latest
    restart: always
    command: prefect worker start --pool "local-push-pool"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./flows:/opt/prefect/flows
    depends_on:
      - prefect-server

volumes:
  prefect-db:
  prefect-server:
